# Generated by Django 4.1.7 on 2023-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
