# Generated by Django 4.1.7 on 2023-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='end',
            field=models.IntegerField(default=0, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='column',
            name='start',
            field=models.IntegerField(default=0, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
