# Generated by Django 4.1.7 on 2023-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_dataset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), (' ', 'Space ( )'), ('|', 'Pipe (|)')], default=',', max_length=2, verbose_name='Column separator'),
        ),
    ]
